-- StudentBnB core seed: five active markets + Portugal reserved and inactive
begin;
insert into public.countries(code,name,locale,currency,domain,active) values
('IT','Italia','it-IT','EUR','casastudent.it',true),
('ES','España','es-ES','EUR','casastudent.es',true),
('FR','France','fr-FR','EUR','casastudent.fr',true),
('DE','Deutschland','de-DE','EUR','casastudent.de',true),
('PL','Polska','pl-PL','PLN','casastudent.pl',true),
('PT','Portugal','pt-PT','EUR','casastudent.pt',false)
on conflict (code) do update set name=excluded.name,locale=excluded.locale,currency=excluded.currency,domain=excluded.domain,active=excluded.active;

insert into public.cities(country_code,slug,name,region,hero_image_url,active) values
('IT','padova','Padova',NULL,NULL,true),
('IT','ancona','Ancona',NULL,NULL,true),
('IT','bari','Bari',NULL,NULL,true),
('IT','bergamo','Bergamo',NULL,NULL,true),
('IT','bologna','Bologna',NULL,NULL,true),
('IT','cagliari','Cagliari',NULL,NULL,true),
('IT','caserta','Caserta',NULL,NULL,true),
('IT','catania','Catania',NULL,NULL,true),
('IT','chieti','Chieti',NULL,NULL,true),
('IT','cosenza-rende','Cosenza–Rende',NULL,NULL,true),
('IT','ferrara','Ferrara',NULL,NULL,true),
('IT','firenze','Firenze',NULL,NULL,true),
('IT','genova','Genova',NULL,NULL,true),
('IT','messina','Messina',NULL,NULL,true),
('IT','milano','Milano',NULL,NULL,true),
('IT','modena','Modena',NULL,NULL,true),
('IT','napoli','Napoli',NULL,NULL,true),
('IT','palermo','Palermo',NULL,NULL,true),
('IT','parma','Parma',NULL,NULL,true),
('IT','pavia','Pavia',NULL,NULL,true),
('IT','perugia','Perugia',NULL,NULL,true),
('IT','pescara','Pescara',NULL,NULL,true),
('IT','pisa','Pisa',NULL,NULL,true),
('IT','reggio-emilia','Reggio Emilia',NULL,NULL,true),
('IT','roma','Roma',NULL,NULL,true),
('IT','salerno-fisciano','Salerno–Fisciano',NULL,NULL,true),
('IT','torino','Torino',NULL,NULL,true),
('IT','trento','Trento',NULL,NULL,true),
('IT','trieste','Trieste',NULL,NULL,true),
('IT','venezia','Venezia',NULL,NULL,true),
('IT','verona','Verona',NULL,NULL,true),
('ES','madrid','Madrid','Comunidad de Madrid','assets/img/citta-madrid.webp',true),
('ES','barcelona','Barcelona','Cataluña','assets/img/citta-barcelona.webp',true),
('ES','valencia','Valencia','Comunitat Valenciana','assets/img/citta-valencia.webp',true),
('ES','sevilla','Sevilla','Andalucía','assets/img/citta-sevilla.webp',true),
('ES','granada','Granada','Andalucía','assets/img/citta-granada.webp',true),
('ES','zaragoza','Zaragoza','Aragón','assets/img/citta-zaragoza.webp',true),
('ES','malaga','Málaga','Andalucía','assets/img/citta-malaga.webp',true),
('ES','murcia','Murcia','Región de Murcia','assets/img/citta-murcia.webp',true),
('ES','alicante','Alicante–San Vicente','Comunitat Valenciana','assets/img/citta-alicante.webp',true),
('ES','salamanca','Salamanca','Castilla y León','assets/img/citta-salamanca.webp',true),
('ES','santiago-de-compostela','Santiago de Compostela','Galicia','assets/img/citta-santiago.webp',true),
('ES','valladolid','Valladolid','Castilla y León','https://commons.wikimedia.org/wiki/Special:FilePath/Valladolid%20-%20Plaza%20Mayor%2002b.jpg?width=1600',true),
('ES','bilbao','Bilbao–Leioa','País Vasco','assets/img/citta-bilbao.webp',true),
('ES','cordoba','Córdoba','Andalucía','assets/img/citta-cordoba.webp',true),
('ES','pamplona','Pamplona','Navarra','https://commons.wikimedia.org/wiki/Special:FilePath/Pamplona%20-%20Plaza%20del%20Castillo%2011.jpg?width=1600',true),
('ES','la-laguna','La Laguna–Santa Cruz','Canarias','https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Junta%20Suprema%2C%20San%20Crist%C3%B3bal%20de%20La%20Laguna%205.jpg?width=1600',true),
('ES','oviedo','Oviedo–Gijón','Asturias','https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20de%20Oviedo%20desde%20Porlier.jpg?width=1600',true),
('ES','alcala-de-henares','Alcalá de Henares','Comunidad de Madrid','https://commons.wikimedia.org/wiki/Special:FilePath/Universidad%20de%20Alcal%C3%A1%20de%20Henares%2C%20fachada.jpg?width=1600',true),
('ES','cadiz','Cádiz–Puerto Real','Andalucía','https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20of%20Cadiz.jpg?width=1600',true),
('FR','paris','Paris','Île-de-France','assets/img/room-1.webp',true),
('FR','lyon','Lyon','Auvergne-Rhône-Alpes','assets/img/room-2.webp',true),
('FR','toulouse','Toulouse','Occitanie','assets/img/room-3.webp',true),
('FR','lille','Lille','Hauts-de-France','assets/img/room-4.webp',true),
('FR','bordeaux','Bordeaux','Nouvelle-Aquitaine','assets/img/room-5.webp',true),
('FR','montpellier','Montpellier','Occitanie','assets/img/room-6.webp',true),
('FR','rennes','Rennes','Bretagne','assets/img/room-7.webp',true),
('FR','nantes','Nantes','Pays de la Loire','assets/img/room-1.webp',true),
('DE','berlin','Berlin','Berlin','assets/img/room-1.webp',true),
('DE','muenchen','München','Bayern','assets/img/room-2.webp',true),
('DE','hamburg','Hamburg','Hamburg','assets/img/room-3.webp',true),
('DE','koeln','Köln','Nordrhein-Westfalen','assets/img/room-4.webp',true),
('DE','frankfurt','Frankfurt am Main','Hessen','assets/img/room-5.webp',true),
('DE','leipzig','Leipzig','Sachsen','assets/img/room-6.webp',true),
('DE','heidelberg','Heidelberg','Baden-Württemberg','assets/img/room-7.webp',true),
('DE','freiburg','Freiburg','Baden-Württemberg','assets/img/room-1.webp',true),
('PL','warszawa','Warszawa','Mazowieckie','assets/img/room-1.webp',true),
('PL','krakow','Kraków','Małopolskie','assets/img/room-2.webp',true),
('PL','wroclaw','Wrocław','Dolnośląskie','assets/img/room-3.webp',true),
('PL','gdansk','Gdańsk','Pomorskie','assets/img/room-4.webp',true),
('PL','poznan','Poznań','Wielkopolskie','assets/img/room-5.webp',true),
('PL','lodz','Łódź','Łódzkie','assets/img/room-6.webp',true),
('PL','lublin','Lublin','Lubelskie','assets/img/room-7.webp',true),
('PL','katowice','Katowice','Śląskie','assets/img/room-1.webp',true),
('PT','lisboa','Lisboa','Área Metropolitana de Lisboa','assets/img/room-1.webp',false),
('PT','porto','Porto','Área Metropolitana do Porto','assets/img/room-2.webp',false),
('PT','coimbra','Coimbra','Região de Coimbra','assets/img/room-3.webp',false),
('PT','braga','Braga','Cávado','assets/img/room-4.webp',false),
('PT','aveiro','Aveiro','Região de Aveiro','assets/img/room-5.webp',false),
('PT','faro','Faro','Algarve','assets/img/room-6.webp',false),
('PT','evora','Évora','Alentejo Central','assets/img/room-7.webp',false),
('PT','covilha','Covilhã','Beiras e Serra da Estrela','assets/img/room-1.webp',false)
on conflict (country_code,slug) do update set name=excluded.name,region=excluded.region,hero_image_url=excluded.hero_image_url,active=excluded.active;
commit;
